name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: write greeting
      run: echo "Hello, World!" > greeting.txt
      - name: print greeting
      run: cat greeting.txt
